
const AuthAPIErr = {
    INVALID_EMAIL: "INVALID_EMAIL",
    NOT_ACTIVE: "NOT_ACTIVE",
    WRONG_PASS: "WRONG_PASS",
    TOKEN_INVALID: "TOKEN_INVALID",
    TOKEN_EXPIRED: "TOKEN_EXPIRED"
};

module.exports = { AuthAPIErr };